# Étape 1 : build Angular
FROM node:22-bullseye AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration=production

# Étape 2 : servir avec Nginx
FROM nginx:stable
COPY --from=build /app/dist/frontend-gamekeeper/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
