# Étape de développement
FROM node:22-bullseye

WORKDIR /usr/src/app

ENV NODE_ENV=development

COPY package*.json ./
RUN npm install -g @angular/cli@20.3.5 && npm install

COPY . .

EXPOSE 4200

CMD ["npm", "run", "start", "--", "--host=0.0.0.0", "--poll=2000"]
